# -*- coding: utf-8 -*-
"""VEX Spin Up 2022-2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vFv1G_2-KfaRzV5ZSF0s6J8k7RZd5ohL
"""

import math

motor_rpm = 200                             # green cartridge
gear_in = 60
gear_out = 12
diameter_flywheel = 4 * 0.0254             # 4 inch times 0.0254 meter/inch
rpm = motor_rpm * gear_in / gear_out
circumference_flywheel = math.pi * diameter_flywheel
flywheel_speed = circumference_flywheel * rpm / 60
k = 1 / 2                                   # factor flywheel_speed / exit_speed
exit_speed = flywheel_speed * k

print(f"The flywheel spins with {rpm} rotations per minute.")
print(f"The exit speed of the disk is {exit_speed} m/s.")

# assuming 45 degrees, v_vertical = v_horizontal
v = math.sqrt(2) * exit_speed
v_i = v
v_f = -v_i
g = -9.81
t = (v_f - v_i) / g
d = v * t
t_h = t / 2
h = 0 + v * t_h + 1/2 * g * t_h **2

print(f"The disk is {t} seconds in the air.")
print(f"It travels {d} meters far.")
print(f"The maximum height is {h} meter.")